version: '3.6'

services:
  db:
    image: mysql:5.7
    volumes:
      - ../config/mysql/my.cnf:/etc/mysql/my.cnf
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeme

  coinhub:
    image: rubykube/coinhub

  redis:
    image: redis:4.0.10
    restart: always
    volumes:
      - redis_data:/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: changeme
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: pma.zenbitex.com'
      traefik.port: 80

  rabbitmq:
    image: rabbitmq:3.7.6-management
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: rabbitmq.zenbitex.com'
      traefik.port: 15672

  vault:
    image: vault:0.10.2
    restart: always
    environment:
      SKIP_SETCAP: 1
      VAULT_TOKEN: changeme
      VAULT_DEV_ROOT_TOKEN_ID: changeme
      VAULT_ADDR: http://vault:8200

  ranger:
    build:
      context: ../app/peatio
    depends_on:
      - rabbitmq
    env_file:
      - ../config/peatio.env
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: ws.ranger.zenbitex.com'
      traefik.port: 8081
    command: bash -c "bundle exec peatio service start ranger"

  mailcatcher:
    image: schickling/mailcatcher
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: mail.zenbitex.com'
      traefik.port: 1080

volumes:
  db_data:
  rabbitmq_data:
  redis_data:
